### ISSUE TITLE
Resource CRUD checklist

### ISSUE THREAD

**Issue by rpkilby** [ITNG/dj-jsonapi#4]
- [x] Basic resource CRUD functionality
- [x] handle side-posting of relationships
- [ ] required relationships should be validated (currently, they will generated a 500)
- [x] API errors (409 conflict) on type mismatch
- [ ] decide on client generated IDs (punt on for now or figure out generic imlementation)
- [x] Fetching included resources
- [ ] review spec for completeness
