### ISSUE TITLE
Resource Relationship checklist

### ISSUE THREAD

**Issue by rpkilby** [ITNG/dj-jsonapi#5]
- [x] Relationship CRUD
- [x] linkage pagination
- [ ] think about read only relationships (vs authorization)
- [ ] audit authorization hooks for relationship updates
- [ ] review spec for completeness, other issues
- [ ] Django GenericRelations
